### ISSUE TITLE
bwtester expects the log file logs/bwtester.log to exist

### ISSUE THREAD

**Issue by hausheer** [perrig/scionlab#23]
If the log file `logs/bwtester.log` doesn't exist, the bwtester fails:

`go run bwtestserver.go -s 3-1034,[127.0.0.1]:30100`
`panic: open logs/bwtester.log: no such file or directory`

It would be nice to specify the log path in a config file.

**Comment by FR4NK-W** [comment]
Good point
Addressed in #24 
Directly using scionproto liblog would be the other option

**Comment by hausheer** [comment]
Thanks that works for me.
